name: API-NEPTUNE

on:
  push:
    branches: [main]

jobs:
  avoid_reduncy:
      runs-on: ubuntu-latest
      steps: 
        - name: Cancel Previus Builds
          uses: styfle/cancel-workflow-action@0.9.1
          with:
            access_token: ${{github.token}}

  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies 
        run: npm ci
      - name: Lint
        run: npm run lint

  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout/@v3
      - name: Set up Node 14
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install Snyk CLI
        run: npm install -g snyk
      - name: run Snyk Open Source Test
        run: snyk test
      - name: run Snyk Code Test
        run: snyk code test

  slack_pull_request:
    needs: [security]
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack pull request open
      if: ${{ github.event_name == 'pull_request' }}
      env: 
        SLACK_WEBHOOK_URL : ${{secrets.SLACK_PULL_REQUEST_WEBHOOK}}
        PULL_REQUEST_NUMBER : ${{ github.event.pull_request.number }}
        PULL_REQUEST_TITLE : ${{ github.event.pull_request.title }}
        PULL_REQUEST_AUTHOR_NAME : ${{ github.event.pull_request.user.login }}
        PULL_REQUEST_AUTHOR_ICON_URL : ${{ github.event.pull_request.user.avatar_url }}
        PULL_REQUEST_URL : ${{ github.event.pull_request.html_url }}
        PULL_REQUEST_BODY : ${{ github.event.pull_request.body }}
        PULL_REQUEST_COMPARE_BRANCH_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
        PULL_REQUEST_COMPARE_BRANCH_NAME : ${{ github.event.pull_request.head.ref }}
        PULL_REQUEST_BASE_BRANCH_OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
        PULL_REQUEST_BASE_BRANCH_NAME : ${{ github.event.pull_request.base.ref }}
        IS_SEND_HERE_MENTION : false
        MAKE_PRETTY : true
        MAKE_COMPACT : true
        IS_PR_FROM_FORK: false
      uses: jun3453/slack-pr-open-notification-action@v1.3.0

  deploy:
    needs: [security]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies 
        run: npm ci
        working-directory: serverless
      - name: Serverless deploy
        if: ${{ github.event_name == 'push' }}
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}